swagger: '2.0'
info:
  title: API Campaña
  description: "Permite listar y crear campañas para un cliente con código único.\n<strong>Ejemplo de uso:</strong> Usamos esta API para que el cliente tenga campañas pre-aprobadas, por ejemplo : Tarjeta, puede ingresar al flujo de venta tarjeta digital . Esta funcionalidad tambien se usa en un bot de Interbank.\n<strong>Parametros Entrada:</strong> Código único de cliente e información de la campaña a crear. \n<strong>Parametros Salida:</strong>Datos de la campaña"
  version: 1.0.0
  x-ibm-name: ms-consultarcampania
host: consultarcampania-UAT.interbankclouduat.pe
basePath: /ms
paths:
  /campania/tarjetas:
    post:
      summary: Registra una campaña de tarjeta para un cliente.
      parameters:
        - in: body
          name: request
          required: true
          schema:
            $ref: '#/definitions/CampaniaTarjeta'
          description: Información de la campaña para cambio de tarjeta de crédito
      responses:
        '200':
          description: Operación Exitosa
          schema:
            $ref: '#/definitions/CrearCampaniaResponse'
  /campania/prestamos:
    post:
      summary: Registra una campaña de préstamo para un cliente.
      parameters:
        - in: body
          name: request
          required: true
          schema:
            $ref: '#/definitions/CampaniaPrestamos'
          description: Información de la campaña para el préstamo
      responses:
        '200':
          description: Operación Exitosa
          schema:
            $ref: '#/definitions/CrearCampaniaResponse'
  '/cliente/{codigoUnicoCliente}/campanias':
    get:
      summary: Registra una campaña de préstamo para un cliente.
      parameters:
        - name: codigoUnicoCliente
          type: string
          required: true
          in: path
          description: Código único del cliente
      responses:
        '200':
          description: 200 OK
          schema:
            $ref: '#/definitions/ClienteCampanias'
definitions:
  CampaniaTarjeta:
    type: object
    properties:
      codigoUnicoCliente:
        type: string
        example: '123456789213'
      marcaTipo:
        type: string
        example: '054'
      descripcionTipoTarjeta:
        type: string
        example: 'Visa Cashback Oro'
      moneda:
        type: string
        example: '001'
      monto:
        type: string
        example: '25000'
      tasaInteresAnual:
        type: integer
        example: 12.9
        format: int32
    description: Contenido de una campaña de tarjeta de crédito
  CampaniaPrestamos:
    type: object
    properties:
      codigoUnicoCliente:
        type: string
        example: '123456789213'
      moneda:
        type: string
        example: '001'
      monto:
        type: string
        example: '25000'
      tasaInteresAnual:
        type: string
        example: 23.5
      plazoMaximo:
        type: string
        example: 12
    description: Contenido de una campaña de prestamos
  ClienteCampanias:
    type: object
    properties:
      tarjetas:
        type: array
        items:
          $ref: '#/definitions/CampaniaTarjeta'
      prestamos:
        type: array
        items:
          $ref: '#/definitions/CampaniaPrestamos'
    description: Lista de Campañas de un cliente
  CrearCampaniaResponse:
    type: object
    properties:
      codigoCampania:
        type: string
        example: '7856745687'
x-ibm-configuration:
  enforced: true
  testable: true
  phase: realized
  cors:
    enabled: true
  assembly:
    execute:
      - operation-switch:
          title: operation-switch
          case:
            - operations:
                - verb: get
                  path: /consultarcampania
              execute:
                - set-variable:
                    title: set-variable
                    actions:
                      - set: message.body
                        value: '[{"codigoUnicoCliente":"0027641514","marcaTipo":"054","descripcionTipoTarjeta":"Visa Cashback Oro","moneda":"001","monto":"5000","tasaInteresAnual":"23.5","codigoCampania":".937103590","nombreProducto":"PRESTAMO EFECTIVO"},{"codigoUnicoCliente":"0027641514","moneda":"001","monto":"5000","tasaInteresAnual":"23.5","plazoMaximo":"12","codigoCampania":".738742491","nombreProducto":"PRESTAMO EFECTIVO"},{"codigoUnicoCliente":"0027641514","moneda":"001","monto":"15000","tasaInteresAnual":"17.5","plazoMaximo":"24","codigoCampania":"1233431","nombreProducto":"CREDITO VEHICULAR"},{"codigoUnicoCliente":"0027641514","moneda":"001","monto":"7000","tasaInteresAnual":"58.0","plazoMaximo":"12","codigoCampania":"1233433","nombreProducto":"TARJETA DORADA"},{"codigoUnicoCliente":"0027641514","moneda":"001","monto":"20000","tasaInteresAnual":"45.0","plazoMaximo":"12","codigoCampania":"12334344","nombreProducto":"TARJETA BLACK"}]'
                      - set: message.headers.content-type
                        value: application/json
                      - set: message.status.code
                        value: '200'
                    version: 1.0.0
                    description: Dummy
            - operations:
                - verb: get
                  path: '/cliente/{codigoUnicoCliente}/campanias'
              execute:
                - proxy:
                    title: proxy
                    timeout: 60
                    verb: keep
                    cache-response: protocol
                    cache-ttl: 900
                    version: 1.0.0
                    target-url: 'https://hackathon-api-server.herokuapp.com/clientes/:codigoUnicoCliente/campanias'
            - operations:
                - verb: post
                  path: /campania/tarjetas
              execute:
                - proxy:
                    title: proxy
                    timeout: 60
                    verb: keep
                    cache-response: protocol
                    cache-ttl: 900
                    version: 1.0.0
                    target-url: 'https://hackathon-api-server.herokuapp.com/campanias/tarjetas'
            - operations:
                - verb: post
                  path: /campania/prestamos
              execute:
                - proxy:
                    title: proxy
                    timeout: 60
                    verb: keep
                    cache-response: protocol
                    cache-ttl: 900
                    version: 1.0.0
                    target-url: 'https://hackathon-api-server.herokuapp.com/campanias/prestamos'
          otherwise: []
          version: 1.0.0
    catch: []
