---
swagger: "2.0"
info:
  title: "API CrearCuentaV2"
  description: "API que sirve para la creación de una cuenta en el Banco. Esta cuenta\
    \ se registrar en el sistema SAVING y se puede crear cuentas de diversos tipos.\n\
    <strong>Ejemplo de uso:</strong> Se utiliza para realizar la apertura de Cuenta\
    \ Digital. Desde otras aplicaciones podemos crear una cuenta al cliente en este\
    \ proceso de valida la identidad del cliente y se envia a crear una cuenta : Simple,\
    \ Sueldo, Millonaria.\n<strong>Parametros Entrada:</strong> código unico del cliente,\
    \ el código producto y subproducto que se quiere crear\n<strong>Parametros Salida:</strong>El\
    \ número de cuenta creada"
  version: "1.0.0"
  x-ibm-name: "ms-crearcuentav2"
host: "crearcuentav2-UAT.interbankclouduat.pe"
basePath: "/ms"
paths:
  /aperturacuenta:
    post:
      parameters:
      - in: "body"
        name: "request"
        required: true
        description: "Registra una cuenta en RM."
        schema:
          $ref: "#/definitions/MessageRequest"
      responses:
        200:
          description: "Conexion exitosa / Error tipo 01: Contraseña incorrecta en\
            \ la credencial del MS./ Error tipo 02: No se ingresa un dato obligatorio\
            \ o formato incorrecto. / Error tipo 03: Cambio de Puerto del MS en el\
            \ Docker./Error tipo 04: Cuando el bus a codificado algo mal en el servicio./Error\
            \ tipo 05: No se ingresa un dato obligatorio o formato incorrecto."
          schema:
            $ref: "#/definitions/MessageResponse"
        401:
          description: "Acceso no autorizado"
        404:
          description: "Ruta no encontrada"
        500:
          description: "Error interno del servicio. Favor intente luego"
definitions:
  MessageRequest:
    type: "object"
    required:
    - "codigoUnicoCliente"
    - "producto"
    - "sProducto"
    - "moneda"
    - "tasaAnual"
    properties:
      codigoUnicoCliente:
        type: "string"
        example: "4568703"
      producto:
        type: "string"
        example: "002"
      sProducto:
        type: "string"
        example: "205"
      moneda:
        type: "string"
        example: "001"
      tasaAnual:
        type: "string"
        example: "110.87"
  MessageResponse:
    type: "object"
    properties:
      numeroCuenta:
        type: "string"
        example: "1007000500767"
x-ibm-configuration:
  enforced: true
  testable: true
  phase: "realized"
  cors:
    enabled: true
  assembly:
    execute:
    - set-variable:
        title: "set-variable"
        actions:
        - set: "message.body"
          value: "{\"header\":{\"response\":{\"serviceId\":\"APE\",\"consumerId\"\
            :\"WEB\",\"moduleId\":\"CUENTA\",\"channelCode\":\"6\",\"messageId\":\"\
            HACKATON_1234567890\",\"timestamp\":\"2017-10-26T10:51:14.675585\",\"\
            countryCode\":\"PE\",\"groupMember\":\"G0003\",\"referenceNumber\":\"\
            48719232_20170920144231699_515\"},\"status\":{\"responseType\":\"0\",\"\
            busResponseCode\":\"0\",\"busResponseMessage\":\"OK\",\"srvResponseCode\"\
            :\"0\",\"srvResponseMessage\":\"EJECUCION CON EXITO\",\"eqvResponseCode\"\
            :\"00\",\"eqvResponseMessage\":\"\",\"messageIdResBus\":\"HACKATON_1234567890\"\
            }},\"body\":{\"controles\":{\"banco\":\"03\",\"moneda\":\"1\",\"producto\"\
            :\"002\"},\"nroCuenta\":\"1007000500767\",\"subProducto\":\"202\",\"tasaEfectiva\"\
            :\"0\",\"nombreBeneficiario\":\"JORGE VEGA\"}}"
        - set: "message.headers.content-type"
          value: "application/json"
        - set: "message.status.code"
          value: "200"
        version: "1.0.0"
        description: "Dummy"
    catch: []
securityDefinitions:
  SecureID:
    type: "apiKey"
    description: ""
    in: "header"
    name: "X-IBM-Client-Id"
security:
- SecureID: []
