---
swagger: "2.0"
info:
  title: "API Obtener Datos Cliente"
  description: "Obtiene datos de un cliente desde RM.\n<strong>Ejemplo de uso:</strong>\
    \ Usamos esta API para obtener el número de codigo único de cliente y realizar\
    \ operaciones con este como creación de cuentas, creación de tarjetas, consultar\
    \ saldos. \n<strong>Parametros Entrada:</strong> Tipo y Nro documento\n<strong>Parametros\
    \ Salida:</strong> Código Unico, Nombres , fecha Nacimiento, sexo, estado civil"
  version: "1.0.0"
  x-ibm-name: "ms-obtenerdatoscontactocliente"
host: "obtenerdatoscontactocliente-UAT.interbankclouduat.pe"
basePath: "/ms"
paths:
  /obtenerdatoscliente:
    get:
      parameters:
      - name: "numeroDocumento"
        in: "query"
        required: true
        description: "Número de documento del cliente"
        type: "string"
        x-example: "02683919"
      responses:
        200:
          description: "Conexion exitosa / Error tipo 01: Contraseña incorrecta en\
            \ la credencial del MS./ Error tipo 02: No se ingresa un dato obligatorio\
            \ o formato incorrecto. / Error tipo 03: Cambio de Puerto del MS en el\
            \ Docker./Error tipo 04: Cuando el bus a codificado algo mal en el servicio./Error\
            \ tipo 05: No se ingresa un dato obligatorio o formato incorrecto."
          schema:
            $ref: "#/definitions/ObtenerDatosClienteResponse"
        401:
          description: "Acceso no autorizado"
        404:
          description: "Ruta no encontrada"
        500:
          description: "Error interno del servicio. Favor intente luego"
definitions:
  ObtenerDatosClienteResponse:
    type: "object"
    required:
    - "apellidoMaterno"
    - "apellidoPaterno"
    - "codigoPaisNacimiento"
    - "codigoPaisNacionalidad"
    - "codigoPaisResidencia"
    - "departamento"
    - "distrito"
    - "email"
    - "estadoCivil"
    - "fechaNacimiento"
    - "listaTelefonos"
    - "nombreVia"
    - "primerNombre"
    - "provincia"
    - "sexo"
    - "tipoDocumento"
    - "tipoEmail"
    - "tipoNacionalidad"
    - "tipoVia"
    properties:
      tipoDocumento:
        type: "string"
        example: "1"
      numeroDocumento:
        type: "string"
        example: "75450500"
      fechaNacimiento:
        type: "string"
        example: "1980-01-01"
      apellidoPaterno:
        type: "string"
        example: "CARDENAS"
      apellidoMaterno:
        type: "string"
        example: "MENDIOLA"
      primerNombre:
        type: "string"
        example: "LORENZO"
      segundoNombre:
        type: "string"
        example: "JEREMIAS"
      sexo:
        type: "string"
        example: "M"
      estadoCivil:
        type: "string"
        example: "U"
      tipoNacionalidad:
        type: "string"
        example: "0"
      codigoPaisNacimiento:
        type: "string"
        example: "4028"
      codigoPaisResidencia:
        type: "string"
        example: "4028"
      codigoPaisNacionalidad:
        type: "string"
        example: "4028"
      tipoVia:
        type: "string"
        example: "av"
      nombreVia:
        type: "string"
        example: "SAN FRANCISCO"
      numeroCalle:
        type: "string"
        example: "258"
      idManzana:
        type: "string"
        example: "A"
      idLote:
        type: "string"
        example: "8"
      idInterior:
        type: "string"
        example: "102"
      nombreUrbanizacion:
        type: "string"
        example: "LOS CONDORES"
      referenciaUbicacion:
        type: "string"
        example: "AL FRENTE DE HOSPITAL CENTRAL"
      departamento:
        type: "string"
        example: "LIMA"
      provincia:
        type: "string"
        example: "LIMA"
      distrito:
        type: "string"
        example: "AREQUIPA"
      listaTelefonos:
        example: []
      tipoEmail:
        type: "string"
        example: "p"
      email:
        type: "string"
        example: "ejemplo@gmail.com"
      codigoCIIU:
        type: "string"
        example: ""
      fechaInicioEmpleo:
        type: "string"
        example: "2015-09-20"
      nombreEmpresa:
        type: "string"
        example: "TELNET S.A."
      codigoOcupacion:
        type: "string"
        example: "EMPLEADO"
x-ibm-configuration:
  enforced: true
  testable: true
  phase: "realized"
  cors:
    enabled: true
  assembly:
    execute:
    - proxy:
        title: "proxy"
        timeout: 60
        verb: "keep"
        cache-response: "protocol"
        cache-ttl: 900
        version: "1.0.0"
        description: "Service"
        target-url: "http://hackathon-3.interbankclouduat.pe:4567/obtenerdatoscontactocliente"
    catch: []
securityDefinitions:
  SecureID:
    type: "apiKey"
    description: ""
    in: "header"
    name: "X-IBM-Client-Id"
security:
- SecureID: []
