swagger: '2.0'
info:
  title: API Pase Cuotas
  description:  |-
    API que realiza el pase  a cuotas. 
    <strong>Ejemplo de uso:</strong> Hemos usado esta API para darle la facilidad al cliente a pasar a un número de cuotas un consumo. 
    Esta funcionalidad esta disponible por la APP y BPI y es una de la más usadas. 
    <strong>Parametros Entrada:</strong>Tarjeta Credito, total cuotas, importe , fecha. 
    <strong>Parametros Salida:</strong> Importe de cuota, tasa, fecha pago
  version: 1.0.0
  x-ibm-name: ms-confirmacioncuotas
host: confirmacioncuotas-UAT.interbankclouduat.pe
basePath: /ms
paths:
  /pasecuotas:
    post:
      parameters:
        - in: body
          name: request
          required: true
          description: Ejecuta un pase a cuotas de un movimiento y devuelve el próximo pago a realizar.
          schema:
            $ref: '#/definitions/PaseCuotasRequest'
      responses:
        '200':
          description: Pase a cuotas exitoso.
          schema:
            $ref: '#/definitions/PaseCuotasResponse'
        '401':
          description: Acceso no autorizado
        '404':
          description: Tarjeta no encontrada
        '500':
          description: Error interno del servicio. Favor intente luego
  /pasecuotas/simulacion:
    post:
      parameters:
        - in: body
          name: request
          required: true
          description: Simula y calcula las cuotas y el próximo pago a realizar.
          schema:
            $ref: '#/definitions/SimulacionCuotasRequest'
      responses:
        '200':
          description: Cálculo de pase a cuotas exitoso.
          schema:
            $ref: '#/definitions/SimulacionCuotaResponse'
  '/pasecuotas/{numeroTarjeta}/cuotas':
    get:
      parameters:
        - name: numeroTarjeta
          in: path
          required: true
          description: Número de tarjeta para listar sus cuotas.
          type: string
      responses:
        '200':
          description: Pase a cuotas exitoso.
          schema:
            $ref: '#/definitions/Cuota'
        '401':
          description: Acceso no autorizado
        '404':
          description: Tarjeta no encontrada
        '500':
          description: Error interno del servicio. Favor intente luego
definitions:
  PaseCuotasRequest:
    required:
      - numeroTarjeta
      - importe
      - cuotas
      - tasaInteresAnual
    properties:
      numeroTarjeta:
        type: string
        example: '12345678001236'
      importe:
        type: number
        example: 150
      cuotas:
        type: number
        example: 4
      tasaInteresAnual:
        type: number
        example: 1.69
  SimulacionCuotaResponse:
    type: object
    properties:
      importeCuota:
        type: number
        example: 56
      proximaFechaPago:
        type: string
        example: '2017-12-05'
  SimulacionCuotasRequest:
    required:
      - importe
      - cuotas
      - tasaInteresAnual
    type: object
    properties:
      importe:
        type: number
        example: 1500
      cuotas:
        type: number
        example: 2
      tasaInteresAnual:
        type: number
        example: 2
  PaseCuotasResponse:
    type: object
    properties:
      totalCuotas:
        type: number
        example: 25.93
      importeCuota:
        type: number
        example: 15
      fechaFacturacion:
        type: string
        example: '2017-01-01'
      interesAnual:
        type: number
        example: 1.49
      saldoDisponible:
        type: number
        example: 1550
  Cuota:
    type: object
    required:
      - numeroTarjeta
      - numeroCuota
    properties:
      numeroTarjeta:
        type: string
        example: '1245686947573444'
      numeroCuota:
        type: string
        example: '1230001'
      montoCutoa:
        type: number
        example: 118
x-ibm-configuration:
  enforced: true
  testable: true
  phase: realized
  cors:
    enabled: true
  assembly:
    execute:
      - operation-switch:
          title: operation-switch
          case:
            - operations:
                - verb: post
                  path: /pasecuotas/simulacion
              execute:
                - proxy:
                    title: proxy
                    timeout: 60
                    verb: keep
                    cache-response: protocol
                    cache-ttl: 900
                    version: 1.0.0
                    target-url: 'https://hackathon-api-server.herokuapp.com/pasecuotas/simulacion'
            - operations:
                - verb: post
                  path: /pasecuotas
              execute:
                - proxy:
                    title: proxy
                    timeout: 60
                    verb: keep
                    cache-response: protocol
                    cache-ttl: 900
                    version: 1.0.0
                    target-url: 'https://hackathon-api-server.herokuapp.com/pasecuotas'
            - operations:
                - verb: get
                  path: '/pasecuotas/{numeroTarjeta}/cuotas'
              execute:
                - proxy:
                    title: proxy
                    timeout: 60
                    verb: keep
                    cache-response: protocol
                    cache-ttl: 900
                    version: 1.0.0
                    target-url: 'https://hackathon-api-server.herokuapp.com/pasecuotas/{numeroTarjeta}/cuotas'
          otherwise: []
          version: 1.0.0
    catch: []
securityDefinitions:
  SecureID:
    type: apiKey
    description: ''
    in: header
    name: X-IBM-Client-Id
security:
  - SecureID: []
produces:
  - application/json
consumes:
  - application/json
