swagger: '2.0'
info:
  title: API FichaReclamo
  description: "Permite gestionar reclamos en el Sistema de Telesoft, este documento es la evidencia de una solicitud y/o reclamo de un cliente del banco.\n<strong>Ejemplo de uso:</strong> al habilitar una tarjeta para compras por internet o viajes al exterior, esto deja una solicitud (ficha).\n<strong>Parametros entrada:</strong> tipo,subtipo,circuito - categoría de la ficha. codigoCliente,codigoEmpresa - identificación del solicitante. \n<strong>Parametros salida:</strong> numeroReclamo - id del reclamo generado."
  version: 1.0.0
  x-ibm-name: ms-generacionfichareclamo
host: 'gestionarReclamos-UAT.interbankclouduat.pe'
basePath: /ms
paths:
  /reclamos:
    post:
      summary: Registra una ficha de reclamo
      parameters:
        - in: body
          name: request
          required: true
          schema:
            $ref: '#/definitions/Reclamo'
      responses:
        '200':
          description: Operación Exitosa
          schema:
            $ref: '#/definitions/CrearFichaReclamoResponse'
  '/reclamos/{numeroReclamo}':
    get:
      summary: Retorna los datos de una ficha de reclamo
      parameters:
        - name: numeroTarjeta
          in: path
          required: true
          description: Número de la Cuenta.
          type: string
      responses:
        '200':
          description: Operación Exitosa
          schema:
            $ref: '#/definitions/FichaReclamo'
  '/clientes/{codigoUnicoCliente}/reclamos':
    get:
      summary: Retorna todos los reclamos de un cliente.
      parameters:
        - name: codigoUnicoCliente
          in: path
          required: true
          description: Código Único del cliente
          type: string
      responses:
        '200':
          description: Operación Exitosa
          schema:
              type: array
              items:
                $ref: '#/definitions/FichaReclamo'
definitions:
  FichaReclamo:
    type: object
    required:
      - codigoUnicoCliente
      - codigoAplicativo
      - estado
      - subtipo
      - tipo
    properties:
      codigoUnicoCliente:
        type: string
        example: '0060030365'
      tipo:
        type: string
        example: '272'
      subtipo:
        type: string
        example: '134'
      estado:
        type: string
        example: 'PENDIENTE'
      descripcion:
        type: string
        example: 'Al cliente no le llego el estado de cuenta del banco por 2 meses'
      fechaAlta:
        type: string
        example: '2017-11-10'
      usuarioDerivado:
        type: string
      codigoAplicativo:
        type: string
        example: 'POSTVENTA'
  CrearFichaReclamoResponse:
    type: object
    properties:
      numeroReclamo:
        type: string
        example: '2727384044'
x-ibm-configuration:
  enforced: true
  testable: true
  phase: realized
  cors:
    enabled: true
  assembly:
    execute:
      - operation-switch:
          title: operation-switch
          case:
            - operations:
                - verb: post
                  path: /reclamos
              execute:
                - proxy:
                    title: proxy
                    timeout: 60
                    verb: keep
                    cache-response: protocol
                    cache-ttl: 900
                    version: 1.0.0
                    description: Service
                    target-url: 'https://hackathon-api-server.herokuapp.com/reclamos'
            - operations:
                - verb: get
                  path: '/reclamos/{numeroReclamo}'
              execute:
                - proxy:
                    title: proxy
                    timeout: 60
                    verb: keep
                    cache-response: protocol
                    cache-ttl: 900
                    version: 1.0.0
                    description: Service
                    target-url: 'https://hackathon-api-server.herokuapp.com/reclamos/{numeroReclamo}'
            - operations:
                - verb: post
                  path: '/reclamos/{numeroReclamo}/abonar'
              execute:
                - proxy:
                    title: proxy
                    timeout: 60
                    verb: keep
                    cache-response: protocol
                    cache-ttl: 900
                    version: 1.0.0
                    description: Service
                    target-url: 'https://hackathon-api-server.herokuapp.com/reclamos/{numeroReclamo}/abonar'
            - operations:
                - verb: get
                  path: '/clientes/{codigoUnicoCliente}/reclamos'
              execute:
                - proxy:
                    title: proxy
                    timeout: 60
                    verb: keep
                    cache-response: protocol
                    cache-ttl: 900
                    version: 1.0.0
                    description: Service
                    target-url: 'https://hackathon-api-server.herokuapp.com/clientes/{codigoUnicoCliente}/reclamos'
          otherwise: []
          version: 1.0.0
    catch: []
securityDefinitions:
  SecureID:
    type: apiKey
    description: ''
    in: header
    name: X-IBM-Client-Id
security:
  - SecureID: []
